### ISSUE TITLE
Loosing access to robot arm, have to restart it manually

### ISSUE THREAD

**Issue by claudfernandes** [ps-micro/PROBOT_Anno#2]
Hi, lots of times when running jobs on the robot arm, it looses access to ROS, it doesn't detect anymore the robot arm, so I need to switch off and switch on the robot arm.

Since I can connect via telnet 192.168.2.123, is there a command that I can restart it remotely, or is there another way to send commands to restart itself?

I tried `telnet 192.168.2.123` and then run the command `reboot`, but keeps just making a single beep non stop, until I switch it off and on again

**Comment by XiangcaiHuang** [comment]
Hi Claudio,
Thanks for your feedback!

> lots of times when running jobs on the robot arm, it looses access to ROS, it doesn't detect anymore the robot arm, so I need to switch off and switch on the robot arm.

There is indeed a bug that caused this issue. We have fixed this bug in v1.1.1 and the controller software stability has been significantly improved. Could you please give me your email address? So that I can send you the docs about SFU tool, and help you upgrade the controller software to v1.1.1. I think you may have a lower version than that.

**Comment by XiangcaiHuang** [comment]
> Since I can connect via telnet 192.168.2.123, is there a command that I can restart it remotely, or is there another way to send commands to restart itself?
> I tried telnet 192.168.2.123 and then run the command reboot, but keeps just making a single beep non stop, until I switch it off and on again

We do not recommend using "reboot" to restart the controller. As you can see, it will make the beep non stop because this command cannot restart the controller completely.

**Comment by claudfernandes** [comment]
Thanks for the help, that is perfect :)

This is my email claudio.fernandes@kreeate.co.uk

**Comment by claudfernandes** [comment]
Thanks for the update.

I will keep testing it.
