### ISSUE TITLE
Is it possible to have English version of the docs ?

### ISSUE THREAD

**Issue by claudfernandes** [ps-micro/PROBOT_Anno#3]
Since the README.md of this repo is also in English is it also possible to have all the documentation in English, it will make it easier to work with this product

https://github.com/ps-micro/PROBOT_Anno/tree/master/docs

**Comment by huchunxu** [comment]
I'm sorry for the trouble caused to you. The English version of the instructions has been uploaded: 
[https://github.com/ps-micro/PROBOT_Anno/tree/master/docs ](https://github.com/ps-micro/PROBOT_Anno/tree/master/docs )

**Comment by claudfernandes** [comment]
No worries, I was using google translate camera to translate from Chinese to English, but this document in english will help alot other people like me that don't speak the language. Thanks :)
